name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - name: chrome
            script: zip
          - name: firefox
            script: zip:firefox
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - run: pnpm install --frozen-lockfile
      - run: pnpm ${{ matrix.script }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.name }}-extension
          path: .output/*.zip
          include-hidden-files: true
          if-no-files-found: error
